//! Garnet source emitter — CIR → Garnet source with sandbox tagging,
//! lineage map, and migrate-todo checklist.

use crate::cir::{Cir, CirLit, CirTy, FuncMode, Ownership};
use crate::error::ConvertError;
use crate::lineage::{LineageMap, WitnessEntry};
use crate::metrics::ConvertMetrics;

#[derive(Debug, Clone, Default)]
pub struct EmitOpts {
    pub source_lang: String,
    pub source_file: String,
    pub target_file: String,
    pub source_loc: usize,
    pub strict: bool, // reject if MigrateTodo or Untranslatable reach emit
    pub fail_on_todo: bool,
    pub fail_on_untranslatable: bool,
}

#[derive(Debug, Clone)]
pub struct EmittedSource {
    pub garnet: String,          // the .garnet source file
    pub lineage_json: String,    // .garnet.lineage.json content
    pub migrate_todo_md: String, // .garnet.migrate_todo.md content
}

/// Emit Garnet source + lineage + migrate-todo checklist from a
/// CIR root. The root is expected to be a Module.
pub fn emit(cir: Cir, opts: EmitOpts) -> Result<(EmittedSource, ConvertMetrics), ConvertError> {
    // Strict-mode checks first
    if (opts.strict || opts.fail_on_todo) && cir.has_migrate_todo() {
        return Err(ConvertError::TodoInStrictMode {
            note: "one or more MigrateTodo annotations reached emit".into(),
            at: opts.source_file.clone(),
        });
    }
    if (opts.strict || opts.fail_on_untranslatable) && cir.has_untranslatable() {
        return Err(ConvertError::UntranslatableInStrictMode {
            reason: "one or more Untranslatable constructs reached emit".into(),
            at: opts.source_file.clone(),
        });
    }

    let mut state = EmitState {
        out: String::new(),
        indent: 0,
        lineage: LineageMap::new(&opts.source_lang, &opts.source_file),
        cir_index: 0,
        line: 1,
        todos: Vec::new(),
    };

    // File header
    state.push_line("# Generated by garnet-convert v0.4.0 — v4.1 SandboxMode default.");
    state.push_line(&format!("# source: {}", opts.source_file));
    state.push_line(&format!("# source-language: {}", opts.source_lang));
    state.push_line("# REVIEW this file end-to-end before changing @sandbox to");
    state.push_line("# @sandbox(unquarantine). Add @caps(...) based on audit findings.");
    state.push_line("");
    state.push_line("@sandbox");
    state.push_line("@caps()");

    emit_cir(&mut state, &cir);

    // Build migrate-todo checklist
    let migrate_todo_md = render_migrate_todo_md(&opts, &state.todos);

    let metrics = ConvertMetrics::from_cir(
        &opts.source_lang,
        &opts.source_file,
        &opts.target_file,
        opts.source_loc,
        &state.out,
        &cir,
    );

    Ok((
        EmittedSource {
            garnet: state.out,
            lineage_json: state.lineage.to_json(),
            migrate_todo_md,
        },
        metrics,
    ))
}

struct EmitState {
    out: String,
    indent: usize,
    lineage: LineageMap,
    cir_index: usize,
    line: usize,
    todos: Vec<TodoEntry>,
}

#[derive(Debug, Clone)]
struct TodoEntry {
    note: String,
    source_span: (usize, usize),
    emit_line: usize,
}

impl EmitState {
    fn push(&mut self, s: &str) {
        for line in s.lines() {
            self.out.push_str(&" ".repeat(self.indent));
            self.out.push_str(line);
            self.out.push('\n');
            self.line += 1;
        }
    }

    fn push_line(&mut self, s: &str) {
        self.push(s);
    }

    fn witness(&mut self, cir: &Cir, kind: &str) {
        self.cir_index += 1;
        let lin = cir.lineage();
        self.lineage.push(WitnessEntry {
            cir_node_id: self.cir_index,
            cir_node_kind: kind.to_string(),
            source_span: lin.source_span,
            emit_line: self.line,
        });
    }
}

fn emit_cir(s: &mut EmitState, cir: &Cir) {
    match cir {
        Cir::Module { name, items, .. } => {
            s.witness(cir, "Module");
            s.push_line(&format!("module {} {{", name));
            s.indent += 2;
            for item in items {
                emit_cir(s, item);
                s.push_line("");
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::Func {
            name,
            params,
            return_ty,
            body,
            mode,
            caps,
            ..
        } => {
            s.witness(cir, "Func");
            let keyword = match mode {
                FuncMode::Safe => "fn",
                _ => "def",
            };
            if !caps.is_empty() {
                s.push_line(&format!("@caps({})", caps.join(", ")));
            }
            let params_rendered = params
                .iter()
                .map(render_param)
                .collect::<Vec<_>>()
                .join(", ");
            let return_part = match return_ty {
                CirTy::Inferred => String::new(),
                other => format!(" -> {}", render_type(other)),
            };
            s.push_line(&format!(
                "{keyword} {name}({params_rendered}){return_part} {{"
            ));
            s.indent += 2;
            for stmt in body {
                emit_cir(s, stmt);
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            s.witness(cir, "If");
            // Render cond inline
            let cond_str = render_expr(cond);
            s.push_line(&format!("if {cond_str} {{"));
            s.indent += 2;
            for stmt in then_b {
                emit_cir(s, stmt);
            }
            s.indent -= 2;
            if let Some(b) = else_b {
                s.push_line("} else {");
                s.indent += 2;
                for stmt in b {
                    emit_cir(s, stmt);
                }
                s.indent -= 2;
            }
            s.push_line("}");
        }
        Cir::While { cond, body, .. } => {
            s.witness(cir, "While");
            s.push_line(&format!("while {} {{", render_expr(cond)));
            s.indent += 2;
            for stmt in body {
                emit_cir(s, stmt);
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::For {
            var, iter, body, ..
        } => {
            s.witness(cir, "For");
            s.push_line(&format!("for {} in {} {{", var, render_expr(iter)));
            s.indent += 2;
            for stmt in body {
                emit_cir(s, stmt);
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::Match {
            scrutinee, arms, ..
        } => {
            s.witness(cir, "Match");
            s.push_line(&format!("match {} {{", render_expr(scrutinee)));
            s.indent += 2;
            for arm in arms {
                let pat = render_expr(&arm.pattern);
                let guard = match &arm.guard {
                    Some(g) => format!(" if {}", render_expr(g)),
                    None => String::new(),
                };
                s.push_line(&format!("{pat}{guard} => {{"));
                s.indent += 2;
                for stmt in &arm.body {
                    emit_cir(s, stmt);
                }
                s.indent -= 2;
                s.push_line("},");
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::Return { value, .. } => {
            s.witness(cir, "Return");
            match value {
                Some(v) => s.push_line(&format!("return {}", render_expr(v))),
                None => s.push_line("return"),
            }
        }
        Cir::Try {
            body,
            catches,
            finally,
            ..
        } => {
            s.witness(cir, "Try");
            s.push_line("try {");
            s.indent += 2;
            for stmt in body {
                emit_cir(s, stmt);
            }
            s.indent -= 2;
            s.push_line("}");
            for catch in catches {
                let binding = match (&catch.binding, &catch.ty) {
                    (Some(b), Some(t)) => format!(" {} : {}", b, render_type(t)),
                    (Some(b), None) => format!(" {}", b),
                    _ => String::new(),
                };
                s.push_line(&format!("rescue{} {{", binding));
                s.indent += 2;
                for stmt in &catch.body {
                    emit_cir(s, stmt);
                }
                s.indent -= 2;
                s.push_line("}");
            }
            if let Some(f) = finally {
                s.push_line("ensure {");
                s.indent += 2;
                for stmt in f {
                    emit_cir(s, stmt);
                }
                s.indent -= 2;
                s.push_line("}");
            }
        }
        Cir::Let {
            name,
            ty,
            mutable,
            value,
            ..
        } => {
            s.witness(cir, "Let");
            let keyword = if *mutable { "let mut" } else { "let" };
            let ty_part = match ty {
                CirTy::Inferred => String::new(),
                other => format!(": {}", render_type(other)),
            };
            let value_part = match value {
                Some(v) => format!(" = {}", render_expr(v)),
                None => String::new(),
            };
            s.push_line(&format!("{keyword} {name}{ty_part}{value_part}"));
        }
        Cir::Struct { name, fields, .. } => {
            s.witness(cir, "Struct");
            s.push_line(&format!("struct {name} {{"));
            s.indent += 2;
            for f in fields {
                let pub_prefix = if f.public { "pub " } else { "" };
                s.push_line(&format!("{pub_prefix}{}: {},", f.name, render_type(&f.ty)));
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::Enum { name, variants, .. } => {
            s.witness(cir, "Enum");
            s.push_line(&format!("enum {name} {{"));
            s.indent += 2;
            for v in variants {
                if v.payload.is_empty() {
                    s.push_line(&format!("{},", v.name));
                } else {
                    let payload = v
                        .payload
                        .iter()
                        .map(render_type)
                        .collect::<Vec<_>>()
                        .join(", ");
                    s.push_line(&format!("{}({payload}),", v.name));
                }
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::Impl {
            target, methods, ..
        } => {
            s.witness(cir, "Impl");
            s.push_line(&format!("impl {target} {{"));
            s.indent += 2;
            for m in methods {
                emit_cir(s, m);
            }
            s.indent -= 2;
            s.push_line("}");
        }
        Cir::MigrateTodo {
            placeholder,
            note,
            lineage,
        } => {
            s.witness(cir, "MigrateTodo");
            s.push_line(&format!("# @migrate_todo: {}", note));
            s.todos.push(TodoEntry {
                note: note.clone(),
                source_span: lineage.source_span,
                emit_line: s.line,
            });
            // Still emit the placeholder — programmers have a value to work with
            emit_cir(s, placeholder);
        }
        Cir::Untranslatable { reason, .. } => {
            s.witness(cir, "Untranslatable");
            s.push_line(&format!("# @untranslatable: {}", reason));
            s.push_line("# (the original construct has no Garnet equivalent; refactor required)");
        }
        // Expressions rendered on their own line as statements
        expr @ (Cir::Literal(..)
        | Cir::Ident(..)
        | Cir::Call { .. }
        | Cir::MethodCall { .. }
        | Cir::FieldAccess { .. }
        | Cir::BinOp { .. }
        | Cir::UnOp { .. }
        | Cir::Assign { .. }
        | Cir::Lambda { .. }
        | Cir::ArrayLit(..)
        | Cir::MapLit(..)
        | Cir::Index { .. }
        | Cir::TupleLit(..)) => {
            s.witness(expr, "Expr");
            s.push_line(&render_expr(expr));
        }
        // Patterns as standalone nodes shouldn't appear at emit top level
        _ => {
            s.witness(cir, "Other");
            s.push_line("# <unrecognized CIR node emitted as placeholder>");
        }
    }
}

fn render_expr(cir: &Cir) -> String {
    match cir {
        Cir::Literal(lit, _) => render_lit(lit),
        Cir::Ident(name, _) => name.clone(),
        Cir::Call { func, args, .. } => {
            let args = args.iter().map(render_expr).collect::<Vec<_>>().join(", ");
            format!("{}({})", render_expr(func), args)
        }
        Cir::MethodCall {
            recv, name, args, ..
        } => {
            let args = args.iter().map(render_expr).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", render_expr(recv), name, args)
        }
        Cir::FieldAccess { recv, name, .. } => {
            format!("{}.{}", render_expr(recv), name)
        }
        Cir::BinOp { op, lhs, rhs, .. } => {
            format!("({} {} {})", render_expr(lhs), op, render_expr(rhs))
        }
        Cir::UnOp { op, operand, .. } => format!("{}{}", op, render_expr(operand)),
        Cir::Assign { lhs, rhs, .. } => {
            format!("{} = {}", render_expr(lhs), render_expr(rhs))
        }
        Cir::Lambda { params, body, .. } => {
            let ps = params
                .iter()
                .map(|p| p.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            if body.len() == 1 {
                format!("|{}| {}", ps, render_expr(&body[0]))
            } else {
                format!("|{}| {{ /* body: {} stmts */ }}", ps, body.len())
            }
        }
        Cir::ArrayLit(items, _) => {
            let inner = items.iter().map(render_expr).collect::<Vec<_>>().join(", ");
            format!("[{inner}]")
        }
        Cir::MapLit(pairs, _) => {
            let inner = pairs
                .iter()
                .map(|(k, v)| format!("{} => {}", render_expr(k), render_expr(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{{inner}}}")
        }
        Cir::Index { recv, key, .. } => format!("{}[{}]", render_expr(recv), render_expr(key)),
        Cir::TupleLit(items, _) => {
            let inner = items.iter().map(render_expr).collect::<Vec<_>>().join(", ");
            format!("({inner})")
        }
        Cir::PatLiteral(lit, _) => render_lit(lit),
        Cir::PatIdent(name, _) => name.clone(),
        Cir::PatTuple(items, _) => {
            let inner = items.iter().map(render_expr).collect::<Vec<_>>().join(", ");
            format!("({inner})")
        }
        Cir::PatEnumVariant { path, payload, .. } => {
            let path = path.join("::");
            if payload.is_empty() {
                path
            } else {
                let inner = payload
                    .iter()
                    .map(render_expr)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{path}({inner})")
            }
        }
        Cir::PatWildcard(_) => "_".to_string(),
        Cir::MigrateTodo { placeholder, .. } => render_expr(placeholder),
        Cir::Untranslatable { reason, .. } => format!("/* untranslatable: {reason} */"),
        _ => "<statement-at-expr-position>".to_string(),
    }
}

fn render_lit(lit: &CirLit) -> String {
    match lit {
        CirLit::Int(n) => n.to_string(),
        CirLit::Float(f) => format!("{f}"),
        CirLit::Str(s) => format!("\"{}\"", escape_str(s)),
        CirLit::Bool(b) => b.to_string(),
        CirLit::Nil => "nil".to_string(),
        CirLit::Symbol(s) => format!(":{s}"),
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

fn render_type(ty: &CirTy) -> String {
    match ty {
        CirTy::Inferred => "_".to_string(),
        CirTy::Concrete(name) => name.clone(),
        CirTy::Optional(inner) => format!("Option<{}>", render_type(inner)),
        CirTy::Array(inner) => format!("Array<{}>", render_type(inner)),
        CirTy::Map(k, v) => format!("Map<{}, {}>", render_type(k), render_type(v)),
        CirTy::Generic(name) => name.clone(),
        CirTy::Result(o, e) => format!("Result<{}, {}>", render_type(o), render_type(e)),
    }
}

fn render_param(p: &crate::cir::Param) -> String {
    let own = match p.ownership {
        Ownership::Borrowed => "borrow ",
        Ownership::Owned => "own ",
        Ownership::MovedIn => "move ",
        Ownership::Default => "",
    };
    match &p.ty {
        CirTy::Inferred => format!("{}{}", own, p.name),
        other => format!("{}{}: {}", own, p.name, render_type(other)),
    }
}

fn render_migrate_todo_md(opts: &EmitOpts, todos: &[TodoEntry]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Migration Todo Checklist — {}\n\nSource: `{}` ({})\nTarget: `{}`\n\n",
        opts.source_file, opts.source_file, opts.source_lang, opts.target_file,
    ));
    if todos.is_empty() {
        out.push_str("No migration todos — conversion was clean.\n");
    } else {
        out.push_str(&format!(
            "## {} item(s) require human review:\n\n",
            todos.len()
        ));
        for (i, t) in todos.iter().enumerate() {
            out.push_str(&format!(
                "- [ ] **{}.** Line {} — source span [{}..{}]: {}\n",
                i + 1,
                t.emit_line,
                t.source_span.0,
                t.source_span.1,
                t.note,
            ));
        }
        out.push_str(
            "\n---\n\nOnce every item is addressed, change `@sandbox` to \
             `@sandbox(unquarantine)` and add appropriate `@caps(...)` to \
             `main` based on your audit.\n",
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cir::Param;
    use crate::cir::{CirLit, FieldDecl, FuncMode};
    use crate::lineage::Lineage;

    fn lin() -> Lineage {
        Lineage::new("rust", "src/foo.rs", 0, 10)
    }

    fn opts() -> EmitOpts {
        EmitOpts {
            source_lang: "rust".into(),
            source_file: "src/foo.rs".into(),
            target_file: "src/foo.garnet".into(),
            source_loc: 100,
            strict: false,
            fail_on_todo: false,
            fail_on_untranslatable: false,
        }
    }

    #[test]
    fn emitter_adds_sandbox_header() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("@sandbox"));
        assert!(e.garnet.contains("@caps()"));
        // Verify @sandbox(unquarantine) only appears in the instructional
        // comment block (lines starting with `#`), never as an active
        // annotation. Per v4.0 SandboxMode, the converter must never emit
        // an un-quarantine annotation — that requires human audit.
        for line in e.garnet.lines() {
            let t = line.trim_start();
            if t.starts_with('#') {
                continue; // comments may reference the un-quarantine syntax
            }
            assert!(
                !t.contains("@sandbox(unquarantine)"),
                "converter must never emit @sandbox(unquarantine) as an annotation; \
                 found on line: {line}"
            );
        }
    }

    #[test]
    fn simple_func_emits_def() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![Cir::Func {
                name: "greet".into(),
                params: vec![],
                return_ty: CirTy::Inferred,
                body: vec![Cir::Literal(CirLit::Str("hello".into()), lin())],
                mode: FuncMode::Managed,
                caps: vec![],
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("def greet()"));
        assert!(e.garnet.contains("\"hello\""));
    }

    #[test]
    fn safe_func_emits_fn() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![Cir::Func {
                name: "hash".into(),
                params: vec![Param {
                    name: "data".into(),
                    ty: CirTy::Concrete("Bytes".into()),
                    ownership: Ownership::Borrowed,
                }],
                return_ty: CirTy::Concrete("Hash".into()),
                body: vec![],
                mode: FuncMode::Safe,
                caps: vec![],
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("fn hash(borrow data: Bytes) -> Hash"));
    }

    #[test]
    fn migrate_todo_emits_comment_and_preserves_placeholder() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![Cir::MigrateTodo {
                placeholder: Box::new(Cir::Literal(CirLit::Nil, lin())),
                note: "ruby method_missing needs @dynamic".into(),
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("@migrate_todo"));
        assert!(e.garnet.contains("ruby method_missing needs @dynamic"));
        assert!(e.migrate_todo_md.contains("method_missing"));
    }

    #[test]
    fn untranslatable_emits_warning_comment() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![Cir::Untranslatable {
                reason: "unsafe block".into(),
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("@untranslatable"));
        assert!(e.garnet.contains("unsafe block"));
    }

    #[test]
    fn strict_mode_rejects_migrate_todo() {
        let cir = Cir::Module {
            name: "Foo".into(),
            items: vec![Cir::MigrateTodo {
                placeholder: Box::new(Cir::Literal(CirLit::Nil, lin())),
                note: "n".into(),
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let mut o = opts();
        o.strict = true;
        match emit(cir, o) {
            Err(ConvertError::TodoInStrictMode { .. }) => {}
            other => panic!("expected strict rejection, got {other:?}"),
        }
    }

    #[test]
    fn struct_emits_braces_and_fields() {
        let cir = Cir::Module {
            name: "M".into(),
            items: vec![Cir::Struct {
                name: "User".into(),
                fields: vec![
                    FieldDecl {
                        name: "id".into(),
                        ty: CirTy::Concrete("Int".into()),
                        public: true,
                    },
                    FieldDecl {
                        name: "name".into(),
                        ty: CirTy::Concrete("String".into()),
                        public: false,
                    },
                ],
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.garnet.contains("struct User {"));
        assert!(e.garnet.contains("pub id: Int"));
        assert!(e.garnet.contains("name: String"));
    }

    #[test]
    fn emit_metrics_has_quarantined_default() {
        let cir = Cir::Module {
            name: "M".into(),
            items: vec![],
            sandbox: true,
            lineage: lin(),
        };
        let (_e, metrics) = emit(cir, opts()).unwrap();
        assert_eq!(
            metrics.sandbox_status,
            crate::metrics::SandboxStatus::Quarantined
        );
    }

    #[test]
    fn lineage_json_emitted() {
        let cir = Cir::Module {
            name: "M".into(),
            items: vec![Cir::Func {
                name: "f".into(),
                params: vec![],
                return_ty: CirTy::Inferred,
                body: vec![],
                mode: FuncMode::Managed,
                caps: vec![],
                lineage: lin(),
            }],
            sandbox: true,
            lineage: lin(),
        };
        let (e, _) = emit(cir, opts()).unwrap();
        assert!(e.lineage_json.contains("\"source_lang\""));
        assert!(e.lineage_json.contains("\"Module\""));
        assert!(e.lineage_json.contains("\"Func\""));
    }
}
