#!/usr/bin/env python3
"""Garnet domain-matrix capture harness (NUC evidence seat): fresh Windows and WSL bundles.

One invocation (`all`) runs, in order, stopping at the first failed gate:
  clone     fresh Windows clone of the public repo, commit identity
  env       environment captures
  baseline  evidence-integrity gate and the readiness test BEFORE any new bundle
  windows   scripts/smoke_garnet_studio_domain_matrix.py on native Windows
  wsl       fresh clone on the WSL ext4 home, the same script there, then a
            byte-verified copy of the WSL bundle into the Windows clone
  verify    manifests, the integrity gate, the readiness test and its lane
  post      post-run state of both clones

Every step is a child process from an argv list (no shell on the Windows side),
stdin closed, stdout and stderr captured unedited into streams/. WSL steps run a
bash script file generated into harness/wsl/ (so no command line is re-quoted);
each script echoes its own exit status as its last stdout line. Every record
carries this file's sha256. The seat's folder is staged outside the clone; the
two domain-matrix bundles are written into the clone by the script that owns
them, as the task specifies.

Usage (Python 3.12, from native PowerShell):
    python w4_capture.py all --stamp YYYYMMDD-HHMM
    python w4_capture.py render --stamp YYYYMMDD-HHMM
"""
from __future__ import annotations

import argparse
import base64
import datetime as dt
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_URL = "https://github.com/Island-Dev-Crew/garnet.git"
STAGE_ROOT = Path(r"C:\gw1-stage\w4")
HOST = os.environ.get("COMPUTERNAME", "UNKNOWN-HOST")
PY312_DIR = r"C:\Users\IslandDevCrew\AppData\Local\Programs\Python\Python312"
PY312 = PY312_DIR + r"\python.exe"
POWERSHELL = os.path.join(os.environ["SystemRoot"], "System32", "WindowsPowerShell", "v1.0", "powershell.exe")
WSL = os.path.join(os.environ["SystemRoot"], "System32", "wsl.exe")
DISTRO = "Ubuntu"
DEFAULT_PATH = os.environ["PATH"]
PINNED_PATH = PY312_DIR + ";" + PY312_DIR + r"\Scripts;" + DEFAULT_PATH
NOREPLY = "275140286+IslandDevCrew@users.noreply.github.com"
TARGET_TEST = "GarnetMitReadinessStatusTests.test_status_distinguishes_plan_completion_from_goal_completion"
CHANGED_EXAMPLES = ("examples/multi_agent_builder.garnet", "examples/agentic_log_analyzer.garnet")
HARNESS_SHA256 = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
NO_PROMPT = {"GIT_TERMINAL_PROMPT": "0"}


class Ctx:
    def __init__(self, stamp: str):
        self.stamp = stamp
        self.clone = rf"C:\gw4-{stamp}"
        self.wsl_clone = f"/root/gw4-{stamp}"
        self.win_bundle_rel = f"proofs/windows/domains/windows-domain-matrix-{stamp}"
        self.wsl_bundle_rel = f"proofs/linux/execution/domains/wsl-domain-matrix-{stamp}"
        self.seat = STAGE_ROOT / f"{stamp}-{HOST}"
        self.log = STAGE_ROOT / f"steps-{stamp}.jsonl"
        self.run_json = STAGE_ROOT / f"run-{stamp}-{HOST}.json"

    def wsl_path(self, p: Path) -> str:
        s = str(p).replace("\\", "/")
        return "/mnt/" + s[0].lower() + s[2:]


def utcnow() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def ps(script: str) -> list[str]:
    blob = base64.b64encode(script.encode("utf-16-le")).decode("ascii")
    return [POWERSHELL, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-EncodedCommand", blob]


def pyc(code: str) -> list[str]:
    return [PY312, "-I", "-c", code]


def step(id, stem, title, argv, display, *, cwd, path="pinned", env=None, timeout=900, script=None,
         script_lang=None, gate=False, section, expect_exit=0):
    return dict(id=id, stem=stem, title=title, argv=argv, display=display, cwd=cwd, path=path, env=env or {},
                timeout=timeout, script=script, script_lang=script_lang, gate=gate, section=section,
                expect_exit=expect_exit)


def ps_step(id, stem, title, script, **kw):
    return step(id, stem, title, ps(script), script, script=script, script_lang="PowerShell 5.1", **kw)


WSL_PRELUDE = (
    "#!/usr/bin/env bash\n"
    "# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.\n"
    "set -euo pipefail\n"
    "trap 'rc=$?; echo \"wsl_script_exit=$rc\"' EXIT\n"
)


def wsl_step(ctx: Ctx, id, stem, title, body: str, **kw):
    text = WSL_PRELUDE + body
    path = ctx.seat / "harness" / "wsl" / f"{id}-{stem}.sh"
    return step(id, stem, title, [WSL, "-d", DISTRO, "--", "bash", ctx.wsl_path(path)],
                f"wsl.exe -d {DISTRO} -- bash harness/wsl/{id}-{stem}.sh", cwd=ctx.clone, script=text,
                script_lang=f"bash (WSL {DISTRO})", **kw) | {"script_path": str(path)}


def read_stream(ctx: Ctx, name: str) -> str:
    return (ctx.seat / "streams" / name).read_text(encoding="utf-8", errors="replace").strip()


MANIFEST_CHECK = (
    "import hashlib, json, re, sys\n"
    "from pathlib import Path\n"
    "ok = True\n"
    "for d in sys.argv[1:]:\n"
    "    b = Path(d); m = b / 'MANIFEST.sha256'\n"
    "    raw = m.read_bytes()\n"
    "    lines = [l.strip() for l in m.read_text(encoding='utf-8').splitlines() if l.strip()]\n"
    "    bad = 0; listed = set()\n"
    "    for l in lines:\n"
    "        g = re.fullmatch(r'([0-9a-f]{64})  ([^\\r\\n]+)', l)\n"
    "        if not g or hashlib.sha256((b / g.group(2)).read_bytes()).hexdigest() != g.group(1): bad += 1\n"
    "        else: listed.add(g.group(2))\n"
    "    on_disk = {p.relative_to(b).as_posix() for p in b.rglob('*') if p.is_file() and p.name != 'MANIFEST.sha256'}\n"
    "    s = json.loads((b / 'garnet-studio-domain-matrix.json').read_text(encoding='utf-8'))\n"
    "    print(f'{d}: manifest_lines={len(lines)} bad={bad} unlisted={sorted(on_disk - listed)} '\n"
    "          f'manifest_crlf={raw.count(bytes([13, 10]))} status={s[\"status\"]} platform={s[\"platform\"]} '\n"
    "          f'arch={s[\"arch\"]} cases={s[\"passed_cases\"]}/{s[\"case_count\"]} '\n"
    "          f'commands={s[\"passed_commands\"]}/{s[\"command_count\"]}')\n"
    "    ok &= bad == 0 and not (on_disk - listed) and s['status'] == 'passed'\n"
    "sys.exit(0 if ok else 1)\n"
)

LANE_PROBE = (
    "import sys\n"
    "sys.path.insert(0, 'scripts')\n"
    "import garnet_mit_readiness_status as m\n"
    "s = m.read_status()\n"
    "lane = {l.id: l for l in s.lanes}['windows_linux_domain_proof_matrix']\n"
    "print('lane status: ' + str(lane.status))\n"
    "print('lane completion_percent: ' + str(lane.completion_percent))\n"
    "print('lane evidence: ' + str(lane.evidence))\n"
    "sys.exit(0 if 'Committed Windows bundle' in str(lane.evidence) else 1)\n"
)


def diff_code(ctx: Ctx) -> str:
    before = ctx.seat / "streams" / "B04-test-file-before.stderr"
    after = ctx.seat / "streams" / "V05-test-file-after.stderr"
    return (
        "import re, sys\n"
        "def parse(p):\n"
        "    t = open(p, 'rb').read().decode('utf-8', 'replace')\n"
        "    bad = set(re.findall(r'^(?:FAIL|ERROR): (\\S+) ', t, re.M))\n"
        "    ran = re.findall(r'^Ran (\\d+) tests', t, re.M)\n"
        "    return bad, ran\n"
        f"b, rb = parse(r'{before}')\n"
        f"a, ra = parse(r'{after}')\n"
        f"target = {TARGET_TEST.split('.')[-1]!r}\n"
        "print('before: ran=' + ','.join(rb) + ' failing=' + ', '.join(sorted(b)))\n"
        "print('after:  ran=' + ','.join(ra) + ' failing=' + ', '.join(sorted(a)))\n"
        "print(f'target failing before: {target in b}; target failing after: {target in a}')\n"
        "print(f'other failures unchanged: {(b - {target}) == a}')\n"
        "sys.exit(0 if target in b and target not in a and (b - {target}) == a and rb == ra else 1)\n"
    )


def steps_for(phase: str, ctx: Ctx) -> list[dict]:
    C = ctx.clone
    if phase == "clone":
        pre = (
            "import os, sys\n"
            f"paths = [r'{C}', r'{C}\\{ctx.win_bundle_rel}']\n"
            "bad = False\n"
            "for p in paths:\n"
            "    e = os.path.exists(p); bad |= e; print(f'{p} exists={e}')\n"
            "sys.exit(1 if bad else 0)\n"
        )
        return [
            step("C00", "precheck", "Windows clone directory absent", pyc(pre), "python -I -c <precheck>",
                 cwd="C:\\", gate=True, section="env"),
            step("C01", "remote-main", "Remote readback of main before cloning (no credential)",
                 ["git", "-c", "credential.helper=", "ls-remote", REPO_URL, "refs/heads/main"],
                 f"git -c credential.helper= ls-remote {REPO_URL} refs/heads/main", cwd="C:\\", env=NO_PROMPT,
                 section="env"),
            step("C02", "clone", "Fresh Windows clone with core.autocrlf=false set before checkout",
                 ["git", "-c", "credential.helper=", "clone", "-c", "core.autocrlf=false", REPO_URL, C],
                 f"git clone -c core.autocrlf=false {REPO_URL} {C}", cwd="C:\\", env=NO_PROMPT, timeout=1800,
                 gate=True, section="env"),
            step("C03", "user-name", "Commit identity for this clone: name",
                 ["git", "-C", C, "config", "user.name", "Jon Isaac"], 'git config user.name "Jon Isaac"',
                 cwd=C, gate=True, section="env"),
            step("C04", "user-email", "Commit identity for this clone: noreply address",
                 ["git", "-C", C, "config", "user.email", NOREPLY], f'git config user.email "{NOREPLY}"',
                 cwd=C, gate=True, section="env"),
        ]
    if phase == "env":
        s = dict(cwd=C, section="env")
        return [
            step("E01", "hostname", "Hostname", ["hostname"], "hostname", **s),
            ps_step("E02", "systeminfo", "OS name, version and system type",
                    'systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"', **s),
            step("E03", "rustc", "Rust compiler (Windows)", ["rustc", "-Vv"], "rustc -Vv", **s),
            step("E04", "cargo", "Cargo (Windows)", ["cargo", "-V"], "cargo -V", **s),
            step("E05", "node", "Node.js", ["node", "-v"], "node -v", **s),
            step("E06", "python-pinned", "python with Python312 first on PATH (every Windows python step uses this)",
                 ["python", "--version"], "python --version", **s),
            step("E07", "where-python-pinned", "Where python resolves on the pinned PATH", ["where.exe", "python"],
                 "where.exe python", **s),
            step("E08", "python-default", "python on the machine's default PATH (disclosure: not the pinned interpreter)",
                 ["python", "--version"], "python --version", path="default", **s),
            step("E09", "git", "Git", ["git", "--version"], "git --version", **s),
            step("E10", "gh-auth", "GitHub CLI auth status (tokens are masked by gh)", ["gh", "auth", "status"],
                 "gh auth status", **s),
            step("E11", "head", "Clone HEAD", ["git", "-C", C, "rev-parse", "HEAD"], "git rev-parse HEAD", gate=True, **s),
            step("E12", "log", "Recent history", ["git", "-C", C, "log", "--oneline", "-6"], "git log --oneline -6", **s),
            step("E13", "status", "Worktree status (must be clean)", ["git", "-C", C, "status", "--short", "--branch"],
                 "git status --short --branch", **s),
            step("E14", "autocrlf", "core.autocrlf at every config level",
                 ["git", "-C", C, "config", "--show-origin", "--get-all", "core.autocrlf"],
                 "git config --show-origin --get-all core.autocrlf", **s),
            step("E15", "identity", "Commit identity in this clone",
                 ["git", "-C", C, "config", "--local", "--get-regexp", "^user\\."],
                 "git config --local --get-regexp ^user\\.", **s),
            step("E16", "check-attr-examples", "Checkout attributes for the two changed example sources",
                 ["git", "-C", C, "check-attr", "text", "eol", "--", *CHANGED_EXAMPLES],
                 "git check-attr text eol -- " + " ".join(CHANGED_EXAMPLES), **s),
            step("E17", "examples-last-change", "Last commit touching the two changed example sources",
                 ["git", "-C", C, "log", "-1", "--format=%H %cI %s", "--", *CHANGED_EXAMPLES],
                 "git log -1 --format='%H %cI %s' -- " + " ".join(CHANGED_EXAMPLES), **s),
            ps_step("E18", "processes", "Process count and OneDrive processes",
                    "$p = Get-Process\n\"process_count=$($p.Count)\"\n"
                    "$p | Where-Object { $_.ProcessName -like '*OneDrive*' } | Sort-Object Id | "
                    "ForEach-Object { \"onedrive_process=$($_.ProcessName) pid=$($_.Id)\" }\n", **s),
            ps_step("E19", "env-vars", "Toolchain-relevant environment variables inherited by every step",
                    "Get-ChildItem env: | Where-Object { $_.Name -match '^(GARNET|CARGO|RUSTUP|RUSTC|RUSTFLAGS|RUST_|PYTHON|GIT_|GH_)' } | "
                    "Sort-Object Name | ForEach-Object { \"$($_.Name)=$($_.Value)\" }\n"
                    "\"(end of GARNET/CARGO/RUST/PYTHON/GIT/GH variables)\"\n", **s),
            ps_step("E20", "wsl-list", "WSL distributions",
                    "wsl.exe -l -v | Out-String | ForEach-Object { $_ -replace \"`0\", '' }\n", **s),
        ]
    if phase == "baseline":
        s = dict(cwd=C, section="baseline")
        return [
            step("B01", "integrity-before", "Evidence-integrity gate before any new bundle",
                 ["python", "scripts/garnet_evidence_integrity_status.py", "--gate"],
                 "python scripts/garnet_evidence_integrity_status.py --gate", **s),
            step("B02", "lane-before", "Domain-matrix readiness lane before any new bundle (expected: not committed)",
                 pyc(LANE_PROBE), "python -I -c <print the windows_linux_domain_proof_matrix lane>", expect_exit=1, **s),
            step("B03", "target-test-before", "The target test before any new bundle (expected red)",
                 ["python", "scripts/test_garnet_mit_readiness_status.py", TARGET_TEST],
                 f"python scripts/test_garnet_mit_readiness_status.py {TARGET_TEST}", expect_exit=1, **s),
            step("B04", "test-file-before", "The whole readiness test file before any new bundle (expected red)",
                 ["python", "scripts/test_garnet_mit_readiness_status.py"],
                 "python scripts/test_garnet_mit_readiness_status.py", timeout=1800, expect_exit=1, **s),
        ]
    if phase == "windows":
        return [
            step("W01", "matrix-windows", "Domain matrix on native Windows (the task's command)",
                 ["python", "scripts/smoke_garnet_studio_domain_matrix.py", "--suite", "all", "--build-cli",
                  "--output-dir", ctx.win_bundle_rel],
                 "python scripts/smoke_garnet_studio_domain_matrix.py --suite all --build-cli --output-dir "
                 + ctx.win_bundle_rel, cwd=C, timeout=3600, gate=True, section="windows"),
        ]
    if phase == "wsl":
        head = read_stream(ctx, "E11-head.stdout")
        W, B = ctx.wsl_clone, ctx.wsl_bundle_rel
        dest = ctx.wsl_path(Path(C)) + "/" + B
        return [
            wsl_step(ctx, "X01", "env", "WSL environment and toolchain",
                     'echo "uname=$(uname -srm)"\n. /etc/os-release && echo "os=$PRETTY_NAME"\n'
                     'echo "user=$(id -un) home=$HOME home_fs=$(stat -f -c %T "$HOME")"\n'
                     f'test ! -e {W} && echo "{W} absent" || {{ echo "{W} already exists"; exit 1; }}\n'
                     'source "$HOME/.cargo/env"\n'
                     "rustc -Vv\ncargo -V\npython3 --version\ngit --version\n"
                     'echo "git_autocrlf_global=[$(git config --global --get core.autocrlf)]"\n',
                     gate=True, section="wsl"),
            wsl_step(ctx, "X02", "clone", "Fresh clone on the WSL ext4 home; HEAD must equal the Windows clone",
                     f"git -c credential.helper= clone -c core.autocrlf=false {REPO_URL} {W} || exit 1\n"
                     f'got=$(git -C {W} rev-parse HEAD); echo "wsl_head=$got"\n'
                     f'echo "windows_head={head}"\n'
                     f'test "$got" = "{head}" || {{ echo "HEAD MISMATCH"; exit 1; }}\n'
                     f"git -C {W} status --short --branch\n"
                     f"git -C {W} config --get core.autocrlf\n"
                     f"sha256sum {W}/{CHANGED_EXAMPLES[0]} {W}/{CHANGED_EXAMPLES[1]}\n",
                     gate=True, section="wsl", timeout=1800),
            wsl_step(ctx, "X03", "matrix-wsl", "Domain matrix in WSL (the task's command, python3 on Linux)",
                     'source "$HOME/.cargo/env"\n'
                     f"cd {W} || exit 1\n"
                     f"python3 scripts/smoke_garnet_studio_domain_matrix.py --suite all --build-cli --output-dir {B}\n",
                     gate=True, section="wsl", timeout=3600),
            wsl_step(ctx, "X04", "bundle-hashes", "WSL bundle: its own manifest check, then sha256 of every file",
                     f"cd {W}/{B} || exit 1\n"
                     "sha256sum -c --quiet MANIFEST.sha256 && echo \"manifest_check=OK\" || exit 1\n"
                     "find . -type f | LC_ALL=C sort | xargs sha256sum\n",
                     gate=True, section="wsl"),
            wsl_step(ctx, "X05", "copy-to-windows", "Copy the WSL bundle into the Windows clone and prove the copy byte-identical",
                     f"src={W}/{B}\ndst={dest}\n"
                     'test ! -e "$dst" || { echo "destination already exists"; exit 1; }\n'
                     'mkdir -p "$(dirname "$dst")" && cp -r "$src" "$dst" || exit 1\n'
                     '( cd "$src" && find . -type f | LC_ALL=C sort | xargs sha256sum ) > /tmp/w4-src.sha\n'
                     '( cd "$dst" && find . -type f | LC_ALL=C sort | xargs sha256sum ) > /tmp/w4-dst.sha\n'
                     'echo "files_src=$(wc -l < /tmp/w4-src.sha) files_dst=$(wc -l < /tmp/w4-dst.sha)"\n'
                     'diff /tmp/w4-src.sha /tmp/w4-dst.sha && echo "copy_identical=True" || { echo "copy_identical=False"; exit 1; }\n'
                     'rm -f /tmp/w4-src.sha /tmp/w4-dst.sha\n',
                     gate=True, section="wsl"),
        ]
    if phase == "verify":
        s = dict(cwd=C, section="verify")
        return [
            step("V01", "manifests", "Both new bundles: manifest (reporter's regex), completeness, summary fields",
                 pyc(MANIFEST_CHECK) + [ctx.win_bundle_rel, ctx.wsl_bundle_rel],
                 f"python -I -c <verify manifests> {ctx.win_bundle_rel} {ctx.wsl_bundle_rel}", **s),
            step("V02", "integrity-after", "Evidence-integrity gate with both new bundles",
                 ["python", "scripts/garnet_evidence_integrity_status.py", "--gate"],
                 "python scripts/garnet_evidence_integrity_status.py --gate", **s),
            step("V03", "lane-after", "Domain-matrix readiness lane with both new bundles",
                 pyc(LANE_PROBE), "python -I -c <print the windows_linux_domain_proof_matrix lane>", **s),
            step("V04", "target-test-after", "The target test with both new bundles",
                 ["python", "scripts/test_garnet_mit_readiness_status.py", TARGET_TEST],
                 f"python scripts/test_garnet_mit_readiness_status.py {TARGET_TEST}", **s),
            step("V05", "test-file-after", "The whole readiness test file, as the task gives it (other failures pre-exist)",
                 ["python", "scripts/test_garnet_mit_readiness_status.py"],
                 "python scripts/test_garnet_mit_readiness_status.py", timeout=1800, expect_exit=1, **s),
            step("V06", "test-file-diff", "B04 vs V05: the target test flips red to green and nothing else changes",
                 pyc(diff_code(ctx)), "python -I -c <compare FAIL/ERROR sets of B04 and V05>", **s),
        ]
    if phase == "post":
        s = dict(cwd=C, section="post")
        return [
            step("P01", "status-windows", "Windows clone status after every step",
                 ["git", "-C", C, "status", "--short", "--branch", "--untracked-files=normal"],
                 "git status --short --branch", **s),
            wsl_step(ctx, "P02", "status-wsl", "WSL clone status after every step",
                     f"git -C {ctx.wsl_clone} status --short --branch\n", section="post"),
            step("P03", "remote-main-after", "Remote readback of main after every step (no credential)",
                 ["git", "-C", C, "-c", "credential.helper=", "ls-remote", "origin", "refs/heads/main"],
                 "git -c credential.helper= ls-remote origin refs/heads/main", env=NO_PROMPT, **s),
            ps_step("P04", "processes-after", "Process count after every step",
                    "\"process_count=$((Get-Process).Count)\"\n", **s),
        ]
    raise SystemExit(f"unknown phase {phase}")


PHASES = ("clone", "env", "baseline", "windows", "wsl", "verify", "post")


def kill_tree(pid: int) -> None:
    subprocess.run(["taskkill", "/T", "/F", "/PID", str(pid)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def run_step(ctx: Ctx, s: dict, phase: str) -> dict:
    env = dict(os.environ)
    env["PATH"] = PINNED_PATH if s["path"] == "pinned" else DEFAULT_PATH
    env.update(s["env"])
    if s.get("script_path"):
        sp = Path(s["script_path"])
        sp.parent.mkdir(parents=True, exist_ok=True)
        sp.write_bytes(s["script"].encode("utf-8"))
    exe = shutil.which(s["argv"][0], path=env["PATH"]) or s["argv"][0]
    argv = [exe] + s["argv"][1:]
    streams = ctx.seat / "streams"
    streams.mkdir(parents=True, exist_ok=True)
    outs = [(streams / f"{s['id']}-{s['stem']}.stdout", "stdout"), (streams / f"{s['id']}-{s['stem']}.stderr", "stderr")]
    cwd = s["cwd"] if Path(s["cwd"]).exists() else "C:\\"
    started, t0, timed_out = utcnow(), time.monotonic(), False
    handles = [open(p, "wb") for p, _ in outs]
    try:
        proc = subprocess.Popen(argv, cwd=cwd, env=env, stdin=subprocess.DEVNULL, stdout=handles[0], stderr=handles[1])
        try:
            rc = proc.wait(timeout=s["timeout"])
        except subprocess.TimeoutExpired:
            timed_out = True
            kill_tree(proc.pid)
            rc = proc.wait()
    finally:
        for h in handles:
            h.close()
    rec = {k: s[k] for k in ("id", "stem", "title", "display", "section", "script", "script_lang", "expect_exit")}
    rec.update(phase=phase, cwd=cwd, argv=argv, resolved_exe=exe, path_mode=s["path"], env_overrides=s["env"],
               started_utc=started, ended_utc=utcnow(), duration_s=round(time.monotonic() - t0, 3), exit_code=rc,
               timed_out=timed_out, timeout_s=s["timeout"], harness_sha256=HARNESS_SHA256,
               script_file=(Path(s["script_path"]).relative_to(ctx.seat).as_posix() if s.get("script_path") else None),
               streams=[{"file": p.relative_to(ctx.seat).as_posix(), "kind": k, "bytes": p.stat().st_size,
                         "sha256": sha256_file(p)} for p, k in outs])
    if (s.get("script_lang") or "").startswith("bash"):
        last = (outs[0][0].read_bytes().rstrip().splitlines() or [b""])[-1].decode("utf-8", "replace")
        rec["wsl_script_exit_line"] = last
    return rec


def cmd_all(ctx: Ctx) -> int:
    if ctx.log.exists() or ctx.seat.exists():
        raise SystemExit(f"refusing to mix runs: {ctx.log} or {ctx.seat} already exists")
    ctx.seat.mkdir(parents=True)
    run = {"harness_sha256": HARNESS_SHA256, "python": sys.executable, "python_version": sys.version,
           "argv": sys.argv, "started_utc": utcnow(), "clone": ctx.clone, "wsl_clone": ctx.wsl_clone,
           "wsl_distro": DISTRO, "stage": str(ctx.seat), "host": HOST, "phases": list(PHASES),
           "stopped_at": None, "unexpected_exits": []}
    for phase in PHASES:
        for s in steps_for(phase, ctx):
            rec = run_step(ctx, s, phase)
            with open(ctx.log, "a", encoding="utf-8", newline="\n") as f:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            flag = "" if rec["exit_code"] == s["expect_exit"] else "  <-- UNEXPECTED EXIT"
            extra = f" [{rec['wsl_script_exit_line']}]" if "wsl_script_exit_line" in rec else ""
            print(f"{rec['id']} {rec['stem']}: exit={rec['exit_code']} (expected {s['expect_exit']}) "
                  f"{rec['duration_s']}s{extra}{flag}", flush=True)
            if flag:
                run["unexpected_exits"].append(rec["id"])
                if s["gate"]:
                    run["stopped_at"] = rec["id"]
                    break
        if run["stopped_at"]:
            print(f"GATE FAILED at {run['stopped_at']}; stopping", flush=True)
            break
    run["ended_utc"] = utcnow()
    ctx.run_json.write_text(json.dumps(run, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    return 2 if run["stopped_at"] else (1 if run["unexpected_exits"] else 0)


# ---------------------------------------------------------------- render ----

def census_row(path: Path, rel: str) -> dict:
    data = path.read_bytes()
    bom = "utf-8" if data.startswith(b"\xef\xbb\xbf") else "utf-16le" if data.startswith(b"\xff\xfe") else \
        "utf-16be" if data.startswith(b"\xfe\xff") else "none"
    try:
        data.decode("utf-8")
        utf8 = True
    except UnicodeDecodeError:
        utf8 = False
    crlf = data.count(b"\r\n")
    lf = data.count(b"\n") - crlf
    cr = data.count(b"\r") - crlf
    endings = ("empty" if not data else "no-newline" if not (crlf or lf or cr) else "CRLF" if crlf and not lf and not cr
               else "LF" if lf and not crlf and not cr else "MIXED")
    return dict(path=rel, bytes=len(data), sha256=hashlib.sha256(data).hexdigest(), utf8=utf8, bom=bom, endings=endings,
                lf=lf, crlf=crlf, cr=cr, nonascii=sum(1 for b in data if b > 127), nul=data.count(0),
                finalnl=data.endswith(b"\n"))


def section_doc(title: str, recs: list[dict], ctx: Ctx, preamble: str) -> bytes:
    out = bytearray(f"# {title}\n{preamble}".encode())
    for r in recs:
        out += b"\n" + b"=" * 78 + b"\n" + f"[{r['id']}] {r['title']}\n".encode()
        if r["script"]:
            out += f"$ ({r['script_lang']}{', ' + r['script_file'] if r['script_file'] else ''})\n  ".encode()
            out += r["script"].rstrip("\n").replace("\n", "\n  ").encode() + b"\n"
        else:
            out += f"$ {r['display']}\n".encode()
        out += (f"exit_code={r['exit_code']} expected={r['expect_exit']} timed_out={r['timed_out']} "
                f"started={r['started_utc']} duration_s={r['duration_s']} path={r['path_mode']}\n").encode()
        for st in r["streams"]:
            raw = (ctx.seat / st["file"]).read_bytes()
            out += f"--- {st['kind']} ({st['file']}, {st['bytes']} bytes, sha256 {st['sha256']})\n".encode() + raw
            if raw and not raw.endswith(b"\n"):
                out += b"\n[no trailing newline in the captured stream]\n"
            out += f"--- end {st['kind']}\n".encode()
    return bytes(out)


def cmd_render(ctx: Ctx) -> None:
    recs = [json.loads(l) for l in ctx.log.read_text(encoding="utf-8").splitlines() if l.strip()]
    run = json.loads(ctx.run_json.read_text(encoding="utf-8"))
    head = (ctx.seat / "streams" / "E11-head.stdout").read_text(encoding="ascii").strip()
    by: dict[str, list] = {}
    for r in recs:
        by.setdefault(r["section"], []).append(r)
    pre = (f"folder: proofs/windows/domain-matrix/{ctx.seat.name}/\n"
           f"bundles: {ctx.win_bundle_rel}/ and {ctx.wsl_bundle_rel}/ (each sealed by its own MANIFEST.sha256,\n"
           "  written by scripts/smoke_garnet_studio_domain_matrix.py)\n"
           f"host: {HOST} (%COMPUTERNAME%; `hostname` prints the DNS casing, see E01)\n"
           f"main: {head}\nstamp: {ctx.stamp} (UTC)\n"
           f"harness: harness/w4_capture.py, sha256 {run['harness_sha256']}; every step ran from this one invocation\n"
           f"  ({' '.join(Path(a).name if i == 0 else a for i, a in enumerate(run['argv']))}), "
           f"{run['started_utc']} to {run['ended_utc']}.\n"
           "python (Windows): every Windows python step ran with Python312 first on PATH except E08, which shows the\n"
           "  machine's default PATH (an unrelated 3.11.15 virtualenv).\n"
           f"wsl: steps X01-X05 and P02 run bash script files (harness/wsl/) inside WSL distro {DISTRO}; each script\n"
           "  prints `wsl_script_exit=<rc>` as its last stdout line, recorded next to wsl.exe's exit code.\n"
           "powershell: PowerShell steps run powershell.exe 5.1 with -EncodedCommand; with redirected output it writes\n"
           "  progress/error records to stderr as CLIXML. The raw streams are authoritative.\n"
           "captures: stdout and stderr are the raw child-process bytes, unedited; see encoding-census.txt.\n")
    docs = {"env.txt": ("Clone and environment captures", ["env"]),
            "baseline.txt": ("Before any new bundle: integrity gate, readiness lane, target test", ["baseline"]),
            "matrix-windows.txt": ("Domain matrix on native Windows", ["windows"]),
            "matrix-wsl.txt": ("Domain matrix in WSL, and the copy into the Windows clone", ["wsl"]),
            "verify.txt": ("After both bundles: manifests, integrity gate, readiness lane, tests, post-run state",
                           ["verify", "post"])}
    for name, (title, sections) in docs.items():
        (ctx.seat / name).write_bytes(section_doc(title, [r for sec in sections for r in by.get(sec, [])], ctx, pre))
    lines = [f"# Commands run for proofs/windows/domain-matrix/{ctx.seat.name}/", pre.rstrip("\n"),
             f"run: stopped_at={run['stopped_at']} unexpected_exits={run['unexpected_exits']}", ""]
    for r in recs:
        lines += ["=" * 78, f"[{r['id']}] {r['title']}   (phase {r['phase']})"]
        if r["script"]:
            lines.append(f"command ({r['script_lang']}{', file ' + r['script_file'] if r['script_file'] else ''}):")
            lines += ["    " + l for l in r["script"].rstrip("\n").split("\n")]
            argv_shown = r["argv"][:-1] + ["<base64 UTF-16LE of the script above>"] if r["script_lang"].startswith(
                "PowerShell") else r["argv"]
        else:
            lines.append(f"command: {r['display']}")
            argv_shown = r["argv"]
        lines += ["argv: " + json.dumps(argv_shown, ensure_ascii=False), f"resolved_exe: {r['resolved_exe']}",
                  f"cwd: {r['cwd']}   path: {r['path_mode']}   env_overrides: {json.dumps(r['env_overrides'])}",
                  f"started_utc: {r['started_utc']}   ended_utc: {r['ended_utc']}   duration_s: {r['duration_s']}",
                  f"exit_code: {r['exit_code']}   expected: {r['expect_exit']}   timed_out: {r['timed_out']}   "
                  f"timeout_s: {r['timeout_s']}"]
        if "wsl_script_exit_line" in r:
            lines.append(f"wsl_script_exit_line: {r['wsl_script_exit_line']}")
        lines += [f"stream: {st['kind']:<7} {st['sha256']}  {st['bytes']:>9} B  {st['file']}" for st in r["streams"]]
    (ctx.seat / "commands.txt").write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
    (ctx.seat / "commands.json").write_bytes(
        (json.dumps({"run": run, "steps": recs}, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode())
    # Census: this folder (except census + manifest) and both script-written bundles, repo-relative paths.
    rows = []
    for rel in sorted(p.relative_to(ctx.seat).as_posix() for p in ctx.seat.rglob("*")
                      if p.is_file() and p.name not in ("MANIFEST.sha256", "encoding-census.txt")):
        rows.append(census_row(ctx.seat / rel, f"proofs/windows/domain-matrix/{ctx.seat.name}/{rel}"))
    for brel in (ctx.win_bundle_rel, ctx.wsl_bundle_rel):
        broot = Path(ctx.clone) / brel
        for rel in sorted(p.relative_to(broot).as_posix() for p in broot.rglob("*") if p.is_file()):
            rows.append(census_row(broot / rel, f"{brel}/{rel}"))
    hdr = (f"{'path':<104} {'bytes':>8} {'utf8':>5} {'bom':>5} {'endings':>10} {'lf':>6} {'crlf':>6} {'cr':>3} "
           f"{'nonascii':>8} {'nul':>3} {'finalnl':>7}  sha256")
    cl = ["# Encoding census (UTF-8 validity, BOM, line endings): this folder plus both domain-matrix bundles",
          "# excludes this file and this folder's MANIFEST.sha256 (both UTF-8, no BOM, LF). Each bundle's own",
          "# MANIFEST.sha256 is listed as written by the smoke script.",
          "# lf = bare LF, crlf = CRLF pairs, cr = lone CR; endings = LF | CRLF | MIXED | no-newline | empty.", "", hdr]
    cl += [f"{r['path']:<104} {r['bytes']:>8} {str(r['utf8']):>5} {r['bom']:>5} {r['endings']:>10} {r['lf']:>6} "
           f"{r['crlf']:>6} {r['cr']:>3} {r['nonascii']:>8} {r['nul']:>3} {str(r['finalnl']):>7}  {r['sha256']}"
           for r in rows]
    (ctx.seat / "encoding-census.txt").write_bytes(("\n".join(cl) + "\n").encode("utf-8"))
    allf = sorted(p.relative_to(ctx.seat).as_posix() for p in ctx.seat.rglob("*")
                  if p.is_file() and p.name != "MANIFEST.sha256")
    (ctx.seat / "MANIFEST.sha256").write_bytes("".join(f"{sha256_file(ctx.seat / r)}  {r}\n" for r in allf).encode())
    print(f"rendered {len(allf)} files + MANIFEST.sha256 in {ctx.seat}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=("all", "render"))
    ap.add_argument("--stamp", required=True)
    a = ap.parse_args()
    ctx = Ctx(a.stamp)
    if a.mode == "render":
        cmd_render(ctx)
        return 0
    return cmd_all(ctx)


if __name__ == "__main__":
    sys.exit(main())
