#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const state = JSON.parse(readFileSync(join(here, "state.json"), "utf8"));
const journal = readFileSync(join(here, "journal.md"), "utf8");
const esc = (value) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const phaseRows = state.phases
  .map((phase) => {
    const passed = phase.gates.filter((gate) => gate.status === "passed").length;
    return `<tr><td>${esc(phase.id)}</td><td>${esc(phase.title)}</td><td>${esc(phase.status)}</td><td>${passed}/${phase.gates.length}</td></tr>`;
  })
  .join("");
const riskRows = state.risks
  .map(
    (risk) =>
      `<li><b>${esc(risk.title)}</b> [${esc(risk.severity)}] — ${esc(risk.note)}</li>`,
  )
  .join("");
const nextRows = state.resume.nextActions
  .map((action) => `<li>${esc(action)}</li>`)
  .join("");
const closeout = state.closeout;

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Garnet Lane 0 Repair #2 — State of the Union</title>
<style>body{margin:0;background:#081018;color:#e8edf6;font:16px/1.5 system-ui}main{max-width:1000px;margin:auto;padding:40px}h1,h2{color:#69d2ff}.card{background:#101c28;border:1px solid #294154;border-radius:12px;padding:20px;margin:18px 0}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #294154;padding:10px;text-align:left}code{color:#ffd27d}.pass{color:#79e2a0}.hold{color:#ffd27d}pre{white-space:pre-wrap}</style></head>
<body><main><h1>Lane 0 Repair #2 — Evidence Durability</h1>
<p>Updated <code>${esc(state.mission.updated)}</code> · stage <b class="pass">${esc(state.archipelago.loop.stage)}</b> · launch <b class="hold">${esc(closeout.launchStatus)}</b></p>
<section class="card"><h2>Verdict</h2><p>All 3/3 bounded claims verified. Windows and Unix clean clones passed without pull refs. Governance remains ${esc(closeout.governanceVerdict)} at band ${closeout.band}/${closeout.bandMaximum}: ${esc(closeout.bandCapReason)}</p></section>
<section class="card"><h2>Phases</h2><table><thead><tr><th>Phase</th><th>Title</th><th>Status</th><th>Gates</th></tr></thead><tbody>${phaseRows}</tbody></table></section>
<section class="card"><h2>Findings</h2><ul>${riskRows}</ul></section>
<section class="card"><h2>Next actions</h2><ol>${nextRows}</ol></section>
<section class="card"><h2>Heartbeat</h2><pre>${esc(journal)}</pre></section>
<p>Generated by <code>ops/lane0-repair2/render-sotu.mjs</code> from namespaced repair state. Do not hand-edit.</p>
</main></body></html>\n`;

writeFileSync(join(here, "state-of-the-union.html"), html, "utf8");
console.log(`Rendered ${join(here, "state-of-the-union.html")}`);
