//! SandboxMode — converter-output default quarantine (v4.0 Security Layer 4).
//!
//! Closes the "v4.1 converter emits unsafe Garnet from crafted source"
//! threat class. Every output of the v4.1 Rust/Ruby/Python → Garnet
//! converter is tagged file-level `@sandbox` which:
//!
//! - Denies all capabilities regardless of what the source code
//!   declares — forces human review before network / filesystem access
//! - Rejects `extern "C"` / `unsafe` constructs even if present in the
//!   original source
//! - Imposes a strict parse budget (half the v3.3 default)
//! - Requires an explicit `@sandbox(unquarantine)` annotation to lift
//!   the sandbox — which MUST be committed by a human reviewer, not
//!   generated by the converter itself

use crate::error::StdError;

/// A sandbox-mode enforcement profile. Applied at program load time
/// for files that carry the `@sandbox` annotation or are emitted by
/// the converter pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SandboxProfile {
    pub deny_all_caps: bool,
    pub reject_unsafe: bool,
    pub reject_extern_c: bool,
    pub max_parse_bytes: usize,
    pub max_ast_depth: u32,
}

impl SandboxProfile {
    /// Default quarantine for converter output. Maximum paranoia.
    pub fn converter_output() -> Self {
        Self {
            deny_all_caps: true,
            reject_unsafe: true,
            reject_extern_c: true,
            max_parse_bytes: 32 * 1024 * 1024, // 32 MiB — half the v3.3 default
            max_ast_depth: 128,
        }
    }

    /// Lifted profile — only available via explicit `@sandbox(unquarantine)`
    /// committed by a human reviewer after audit.
    pub fn unquarantined() -> Self {
        Self {
            deny_all_caps: false,
            reject_unsafe: false,
            reject_extern_c: false,
            max_parse_bytes: 64 * 1024 * 1024, // regular v3.3 default
            max_ast_depth: 256,
        }
    }
}

/// Quarantine status of a compilation unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SandboxStatus {
    /// `@sandbox` annotation present and no `@sandbox(unquarantine)` —
    /// apply `converter_output()` profile.
    Quarantined,
    /// `@sandbox(unquarantine)` annotation present — human has audited.
    Unquarantined,
    /// Normal code, not produced by the converter.
    NotSandboxed,
}

/// Decision for a capability request under the given sandbox profile.
pub fn check_cap_permitted(
    profile: &SandboxProfile,
    requested_cap: &str,
) -> Result<(), StdError> {
    if profile.deny_all_caps {
        return Err(StdError::CapsMissing {
            prim: format!("(sandboxed code)"),
            required: requested_cap.to_string(),
        });
    }
    Ok(())
}

/// Parse a `@sandbox(...)` annotation body and produce the status.
/// Accepts: `@sandbox` → Quarantined, `@sandbox(unquarantine)` → Unquarantined.
pub fn parse_sandbox_arg(arg: Option<&str>) -> SandboxStatus {
    match arg {
        None => SandboxStatus::Quarantined,
        Some("unquarantine") => SandboxStatus::Unquarantined,
        Some(_) => SandboxStatus::Quarantined, // unknown arg = most-paranoid
    }
}

/// Produce the active profile based on sandbox status.
pub fn active_profile(status: SandboxStatus) -> Option<SandboxProfile> {
    match status {
        SandboxStatus::Quarantined => Some(SandboxProfile::converter_output()),
        SandboxStatus::Unquarantined => None, // normal rules apply
        SandboxStatus::NotSandboxed => None,
    }
}

/// Diagnostic: is the caller trying to use a feature that sandbox
/// forbids? Called from the v4.1 converter output validator.
pub fn reject_unsafe_constructs(
    profile: &SandboxProfile,
    construct_kind: &str,
) -> Result<(), String> {
    if profile.reject_unsafe && construct_kind == "unsafe" {
        return Err(
            "sandboxed code cannot use `unsafe`; audit + add @sandbox(unquarantine) first".into(),
        );
    }
    if profile.reject_extern_c && construct_kind == "extern_c" {
        return Err(
            "sandboxed code cannot declare `extern \"C\"`; audit first".into(),
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quarantined_denies_all_caps() {
        let profile = SandboxProfile::converter_output();
        for cap in &["fs", "net", "time", "proc", "ffi"] {
            match check_cap_permitted(&profile, cap) {
                Err(StdError::CapsMissing { .. }) => {}
                other => panic!("expected CapsMissing for {cap}, got {other:?}"),
            }
        }
    }

    #[test]
    fn unquarantined_permits_caps() {
        let profile = SandboxProfile::unquarantined();
        for cap in &["fs", "net", "time"] {
            assert!(check_cap_permitted(&profile, cap).is_ok());
        }
    }

    #[test]
    fn sandbox_arg_parsing() {
        assert_eq!(parse_sandbox_arg(None), SandboxStatus::Quarantined);
        assert_eq!(
            parse_sandbox_arg(Some("unquarantine")),
            SandboxStatus::Unquarantined
        );
        assert_eq!(parse_sandbox_arg(Some("bogus")), SandboxStatus::Quarantined);
    }

    #[test]
    fn active_profile_for_each_status() {
        assert!(active_profile(SandboxStatus::Quarantined).is_some());
        assert!(active_profile(SandboxStatus::Unquarantined).is_none());
        assert!(active_profile(SandboxStatus::NotSandboxed).is_none());
    }

    #[test]
    fn reject_unsafe_fires() {
        let profile = SandboxProfile::converter_output();
        assert!(reject_unsafe_constructs(&profile, "unsafe").is_err());
        assert!(reject_unsafe_constructs(&profile, "extern_c").is_err());
        assert!(reject_unsafe_constructs(&profile, "normal").is_ok());
    }

    #[test]
    fn unquarantined_allows_unsafe() {
        let profile = SandboxProfile::unquarantined();
        assert!(reject_unsafe_constructs(&profile, "unsafe").is_ok());
    }

    #[test]
    fn parse_bytes_limit_stricter_in_sandbox() {
        let q = SandboxProfile::converter_output();
        let u = SandboxProfile::unquarantined();
        assert!(q.max_parse_bytes < u.max_parse_bytes);
        assert!(q.max_ast_depth < u.max_ast_depth);
    }
}
