#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
git -C /root/gw4-20260924-1247 status --short --branch
