#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
echo "uname=$(uname -srm)"
. /etc/os-release && echo "os=$PRETTY_NAME"
echo "user=$(id -un) home=$HOME home_fs=$(stat -f -c %T "$HOME")"
test ! -e /root/gw4-20260924-1247 && echo "/root/gw4-20260924-1247 absent" || { echo "/root/gw4-20260924-1247 already exists"; exit 1; }
source "$HOME/.cargo/env"
rustc -Vv
cargo -V
python3 --version
git --version
echo "git_autocrlf_global=[$(git config --global --get core.autocrlf)]"
