#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
git -c credential.helper= clone -c core.autocrlf=false https://github.com/Island-Dev-Crew/garnet.git /root/gw4-20260924-1247 || exit 1
got=$(git -C /root/gw4-20260924-1247 rev-parse HEAD); echo "wsl_head=$got"
echo "windows_head=dfb9b7c619b0f356bf7905a7542080f679fb9bd9"
test "$got" = "dfb9b7c619b0f356bf7905a7542080f679fb9bd9" || { echo "HEAD MISMATCH"; exit 1; }
git -C /root/gw4-20260924-1247 status --short --branch
git -C /root/gw4-20260924-1247 config --get core.autocrlf
sha256sum /root/gw4-20260924-1247/examples/multi_agent_builder.garnet /root/gw4-20260924-1247/examples/agentic_log_analyzer.garnet
