#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
source "$HOME/.cargo/env"
cd /root/gw4-20260924-1247 || exit 1
python3 scripts/smoke_garnet_studio_domain_matrix.py --suite all --build-cli --output-dir proofs/linux/execution/domains/wsl-domain-matrix-20260924-1247
