#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
cd /root/gw4-20260924-1247/proofs/linux/execution/domains/wsl-domain-matrix-20260924-1247 || exit 1
sha256sum -c --quiet MANIFEST.sha256 && echo "manifest_check=OK" || exit 1
find . -type f | LC_ALL=C sort | xargs sha256sum
