#!/usr/bin/env bash
# Generated by w4_capture.py; runs inside WSL (distro Ubuntu) as the default user.
set -euo pipefail
trap 'rc=$?; echo "wsl_script_exit=$rc"' EXIT
src=/root/gw4-20260924-1247/proofs/linux/execution/domains/wsl-domain-matrix-20260924-1247
dst=/mnt/c/gw4-20260924-1247/proofs/linux/execution/domains/wsl-domain-matrix-20260924-1247
test ! -e "$dst" || { echo "destination already exists"; exit 1; }
mkdir -p "$(dirname "$dst")" && cp -r "$src" "$dst" || exit 1
( cd "$src" && find . -type f | LC_ALL=C sort | xargs sha256sum ) > /tmp/w4-src.sha
( cd "$dst" && find . -type f | LC_ALL=C sort | xargs sha256sum ) > /tmp/w4-dst.sha
echo "files_src=$(wc -l < /tmp/w4-src.sha) files_dst=$(wc -l < /tmp/w4-dst.sha)"
diff /tmp/w4-src.sha /tmp/w4-dst.sha && echo "copy_identical=True" || { echo "copy_identical=False"; exit 1; }
rm -f /tmp/w4-src.sha /tmp/w4-dst.sha
